# Generated by Django 3.2.3 on 2021-05-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0002_auto_20210528_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
